
#define WIN_WIDTH 800
#define WIN_HEIGHT 600
#define CELL_SIZE 50
#define CHUNK_SIZE 16

// #define PLAYER_FRICTION_MULTIPLIER 5
#define PLAYER_SPEED_MULTIPLIER 50
#define INITIAL_PLAYER_JUMP_FORCE 10;
#define GRAVITY_MULTIPLIER 200